# Generated by Django 4.2 on 2023-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='adress',
            field=models.TextField(),
        ),
    ]
