# Generated by Django 4.2 on 2023-12-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
