# Generated by Django 4.2 on 2023-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_airport_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'kelasor Flight'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(help_text='price in Rial'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_number',
            field=models.IntegerField(verbose_name='capacity'),
        ),
    ]
