# Generated by Django 4.2 on 2023-12-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('adress', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('seats_number', models.IntegerField(verbose_name='capacity')),
                ('price', models.FloatField(help_text='price in Rial')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.station')),
            ],
        ),
    ]
